interface PackageJsonRequirements {
  author: string;
  license: string;
  name: string;
  repository: string;
  version: string;
}

export default function packageJsonTemplate(
  requirements: PackageJsonRequirements,
) {
  const { author, license, name, repository, version } = requirements;
  return `{
  "name": "${name}",
  "version": "${version}",
  "description": "Client generated by dumb-node-rpc.",
  "main": "dist/index.js",
  "scripts": {
    "build": "npx tsc",
    "integration-test": "npx ts-node src/index.ts | npx bunyan",
    "test": "echo \\"Error: no test specified\\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+${repository}"
  },
  "author": "${author}",
  "license": "${license}",
  "devDependencies": {
    "@types/node": "^14.14.2",
    "ts-node": "^9.0.0",
    "typescript": "^4.0.3"
  },
  "dependencies": {
    "@danielemeryau/dumb-node-rpc-base-client": "^0.0.2",
    "@danielemeryau/logger": "^0.1.1"
  }
}`;
}
