import PackageJsonRequirements from '../shared/packageJsonRequirements';

export default function packageJsonTemplate(
  requirements: PackageJsonRequirements,
) {
  const { author, license, name, version } = requirements;
  return `{
  "name": "${name}",
  "version": "${version}",
  "description": "Client generated by dumb-node-rpc.",
  "main": "dist/client.js",
  "scripts": {
    "build": "npx tsc"
  },
  "author": "${author}",
  "license": "${license}",
  "devDependencies": {
    "typescript": "^4.0.3"
  },
  "dependencies": {
    "@danielemeryau/dumb-node-rpc-base-client": "0.0.3"
  }
}`;
}
